id: "draw-image"
version: "1.0.0"
type: "application"
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-lang-core.git
  - id: am-png
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-imaging-png.git

platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc -O3
    asmCommand: vasmm68k_mot
    linkerCommand: m68k-amigaos-gcc
    gccAdditionalLibraries:
    additionalHeaders:
    additionalAsmSources:
    additionalCSources:
    additionalIncludePaths:      
    gccAdditionalOptions:
      - -noixemul
    additionalLinkerFlags:
      - -noixemul
  - id: linux-x64
    extends: libc
    gccCommand: gcc -O3
    linkerCommand: gcc
    gccAdditionalLibraries:
    additionalHeaders:
    additionalAsmSources:
    additionalCSources:
    additionalIncludePaths:      
    gccAdditionalOptions:
    additionalLinkerFlags:
buildTargets:
  - id: amigaos_docker
    platform: amigaos
    dockerBuild: 
      image: amiga-gcc
      buildPath: /host
  - id: linux-x64
    platform: linux-x64
