
id: am-imaging-png
version: 1.0.0
type: library
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    branch: master
    url: https://github.com/anderskjeldsen/am-lang-core.git
  - id: am-imaging
    realm: github
    type: git-repo
    tag: latest
    branch: master
    url: https://github.com/anderskjeldsen/am-imaging.git
platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc
    asmCommand: vasmm68k_mot
    gccAdditionalLibraries:
      - socket
    additionalHeaders:
    additionalAsmSources:
    additionalCSources:
    additionalIncludePaths:
      - c-libs/libpng15/include
      - c-libs/zlib/nofpu/include
    gccAdditionalOptions:
      - -noixemul     
      - -L c-libs/libpng15/lib
      - -l png15
      - -L c-libs/zlib/nofpu/lib
      - -l z
  - id: macos-arm
    extends: libc
    gccCommand: gcc
    additionalHeaders:
    additionalAsmSources:
    additionalCSources:
    additionalIncludePaths:
      - /opt/homebrew/include
#      - c-libs/zlib/nofpu/include
    gccAdditionalOptions:
      - -L /opt/homebrew/lib
      - -l png
#      - -L c-libs/zlib/nofpu/lib
#      - -l z
buildTargets:
  - id: amigaos_docker
    platform: amigaos
    dockerBuild:
      image: kjeldsenanders/dnf-dev:initial-x86
      buildPath: /host
  - id: amigaos_docker_arm
    platform: amigaos
    dockerBuild:
      image: kjeldsenanders/dnf-dev:initial
      buildPath: /host
  - id: macos-arm
    platform: macos-arm
    commands:
      - make -f macos-arm.Makefile all
